### ISSUE TITLE
format of profile .yml

### ISSUE THREAD

**Issue by bofrost007** [seanhamlin/site-audit#128]
When I create a new profile (profile:generate) it creates a .yml file, where all strings are in quotes:
policies:
    'Acquia:AgentEnabled': {  }
    'Acquia:Connected': {  }
(same with the Acquia default profile)
    
By looking to the default D8/D7 profiles it is without:
policies:
  Drupal-7:NoDuplicateModules: {}
 
I think we should use the same structure everywhere.

**Comment by fiasco** [comment]
the quotes are provided by `Yaml::dump` when we write the file. I personally don't like the quotes as I think it makes it harder to read but I'm not sure I can configure `Yaml::dump` to not print them?

**Comment by fiasco** [comment]
There are now docs on profiles too: http://drutiny.readthedocs.io/en/latest/profiles/
Please feel free to reopen if there are any actionable changes we could make.
