### ISSUE TITLE
Policy Warnings

### ISSUE THREAD

**Issue by bofrost007** [seanhamlin/site-audit#134]
I have created a new policy including a warning check.
But if it is a warning, Drutiny gives me always the failure message instead of the warning.

**Comment by bofrost007** [comment]
I tried it with this new check https://github.com/drutiny/drutiny/pull/135

**Comment by fiasco** [comment]
In 2.x I wanted `audit()` functions to return standard PHP return values:

- `TRUE` = pass
- `FALSE` = fail
- `NULL` = N/A

This doesn't provide an option for returning a warning. So instead, I plan to support warnings through Exceptions.

- `AuditWarningException` - when an audit passes with warnings
- `AuditNotApplicableException` - when an audit is not applicable to the target site
- `AuditFatalErrorException` - when the audit itself fails to complete and make an assessment.

These are not implemented yet, but any feedback on the proposed approach would be great.

**Comment by seanhamlin** [comment]
The main issue with throwing exceptions is that you need to catch them, where as returning constants is easy to read and understand.

Still a fan of `AuditResponse::Warning`.

Throwing exceptions like `AuditNotApplicableException()` makes sense as this is a short circuit normally, and keeps the code easy to read.

**Comment by fiasco** [comment]
Catching them is the easy part as this can be taken care of in the Sandbox. Constructing a `AuditWarningException` however could be non-intuitive. 

Also worth noting that `AuditFatalErrorException` would not be thrown by the audit method itself but an internal it used such as `Sandbox::exec` or `Sandbox::drush`

**Comment by bofrost007** [comment]
If we allow warnings as a regular response and you can configure/ define warnings in the yaml than it  shouldn't be a exception. Because, it is not a exception, it is an expected behavior.
If you would ask me, I would vote for Sean's way.

**Comment by fiasco** [comment]
I've reimplemented warnings based on return constants and have documented them here: http://drutiny.readthedocs.io/en/latest/audits/#return-values
