### ISSUE TITLE
Drush sqlq with Drupal 8

### ISSUE THREAD

**Issue by bofrost007** [seanhamlin/site-audit#137]
If you run an audit against Drupal 8 and your check is using "drush sqlq", it fails with the following error:
Fatal error: Class 'Database' not found in /mnt/www/html/xxxxxxx/vendor/drush/drush/lib/Drush/Sql/SqlBase.php on line 204
Drush command terminated abnormally due to an unrecoverable error.                                                               [error]
Error: Class 'Database' not found in /mnt/www/html/xxxxxxx/vendor/drush/drush/lib/Drush/Sql/SqlBase.php, line
204

The issue is coming from DrushTrait.php line 74
If you remove the --db-prefix argument it is working. But I am not sure if we need the prefix arg somewhere else.

Please check for your self with "./vendor/bin/drutiny policy:audit Drupal:AnonSession @xx.xx -vvv"

**Comment by fiasco** [comment]
The `--db-prefix` flag is required to prefix tables in SQL. E.g. change {tablename} to prefix_tablename. If this is a Drupal 7 only thing then we may need to better understand how to achieve the same ends in Drupal 8 (or is --db-prefix now implied?)

**Comment by bschilt** [comment]
I've hit this same issue with the "Drupal:largeFiles" policy. It works for D7 but not with D8. Here is a comment from Moshe, stating that db-prefix is no longer supported in Drush: 
https://github.com/drush-ops/drush/issues/1441#issuecomment-327179972

There's also this: https://www.drupal.org/project/drush/issues/1389438

**Comment by fiasco** [comment]
@bschilt which version of drush were you using?

Drush behaves different between versions of drush too which makes supporting many versions of drush insite drutinty quite difficult.

**Comment by bschilt** [comment]
This was my error message:
```
Fatal error: Class 'Database' not found in /usr/local/drush8/vendor/drush/drush/lib/Drush/Sql/SqlBase.php on line 204
```

So looks like Drush 8:
```
/usr/local/drush8/vendor/drush/drush$ ./drush --version
 Drush Version   :  8.1.12
```

**Comment by fiasco** [comment]
the use of `--db-prefix` was removed in 8477991081d4b6efdce0bcf01188673ba5b7f200
