### ISSUE TITLE
Link to Contributing guide is broken on symlink README.md

### ISSUE THREAD

**Issue by rsau** [seanhamlin/site-audit#142]
Link to Contributing guide is 
`https://github.com/drutiny/drutiny/blob/2.x/CONTRIBUTING.md`  in `README.md` at `https://github.com/drutiny/drutiny`. It doesn't exist because `README.md` is symlinked to `docs/README.md` which points to correct contributing guide at `https://github.com/drutiny/drutiny/blob/2.x/docs/CONTRIBUTING.md` but when contributing guide link is clicked from root `README.md` github does 404 as it is trying to find `CONTRIBUTING.md` at root level. 

If I create symlink to `CONTRIBUTING.md` at root level Github just display link info and not the file. 

Using absolute path fixes the issue but I am sure that is not the right solution.

**Comment by fiasco** [comment]
Fixed in 2.1.x
