### ISSUE TITLE
Theme checks on 1.x branch don't work for non-ACSF sites

### ISSUE THREAD

**Issue by tobybellwood** [seanhamlin/site-audit#148]
Is there a more generic way to build a path to a theme using getCoreStatus if we add in the 'themes' and 'theme' functions?
Currently it works on acsf, but has to be modified to work on ACE
(e.g. /mnt/www/html/siteds2slxxer8/docroot / sites/all/themes / site_theme )

```
acsf: cd {$root}/{$site}/themes/site/
ace: cd {$root}/{$themes}/{$theme}/ 
```
This would then allow us to perform better pre-forklift checks for govCMS?

**Comment by fiasco** [comment]
I believe the ported checks in 2.x now provide policies for both.
