### ISSUE TITLE
Print CSS

### ISSUE THREAD

**Issue by CashWilliams** [seanhamlin/site-audit#150]
Currently the html version of the report lacks proper CSS for printing, or using print to PDF.

**Comment by fiasco** [comment]
I am by no means a guru in this area and welcome some help! This is the standard page twig file: https://github.com/drutiny/drutiny/blob/2.x/src/Report/templates/page.html.twig 

Note that it can be overwritten by a profile to allow profiles to be themed based on their use.

The report renders bootstrap savvy HTML. Happy to consider any recommendations to make the report more pleasant.

**Comment by ghazlewood** [comment]
I've looked at the print css today for the default report template and it looks pretty good to me, I think this can be closed. Additional print styles were added in https://github.com/drutiny/drutiny/commit/eed8917be8fbec9f7875456448ce4dc18bfe4578

**Comment by fiasco** [comment]
I have put some work into the print stylesheet lately so am happy to close.
