### ISSUE TITLE
Fatal error: Call to a member function isSuccessful()

### ISSUE THREAD

**Issue by bofrost007** [seanhamlin/site-audit#154]
After running a profile against  ACSF (by using the acquia plugin) I get an fatal error.

Steps to reproduce:
1. Add acquia plugin to Drutiny
2. Run ./vendor/bin/drutiny site-factory:profile:run any-profile @example.01live --factory=https://www.blabla.com --api-username=xyz --api-key=abc0123

Result:
```
PHP Fatal error:  Call to a member function isSuccessful() on array in /xyz/vendor/drutiny/drutiny/src/Report/ProfileRunReport.php on line 52
```

**Comment by bofrost007** [comment]
to be honest, I do not get the sense of that sorting... maybe we don't need it at all.

**Comment by fiasco** [comment]
The purpose of that sorting behaviour is to raise failures and high severity issues to the top of a report as these are the things you'll first want to know about.

If you look at a security pen test report, you'll notice that the issues reported are ordered by highest severity first. So this seems to be a good standard to take.

The fact an array is being passed opposed to the AuditResponse object is the bigger issue.

**Comment by bofrost007** [comment]
happens also on a normal audit with multiple URIs

**Comment by fiasco** [comment]
Its because the report should be using `ProfileRunMultisiteReport` instead of `ProfileRunReport`

**Comment by fiasco** [comment]
Ah, its because ProfileRunMultisiteReport uses the same __constructor method.

**Comment by fiasco** [comment]
That should fix it. Protip: When testing drutiny functionality - use the `test` profile as it uses test policies which don't actually evaluate anything. This allow the profile to run much quicker.
