### ISSUE TITLE
autoload.php error

### ISSUE THREAD

**Issue by ainsofs** [seanhamlin/site-audit#161]
Fatal error: require(): Failed opening required 'vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/html/vendor/drutiny/drutiny/bin/drutiny on line 31
--
It seems drutiny cannot found my autoload file. When I edit vendor/drutiny/drutiny/bin/drutiny and hardcode my autoload file to /var/www/vendor/autoload.php the error disappears

My partial Drupal directory structure is as below:
composer.json
vendor
web
> core
> modules
...

I run drutiny from web folder, and get the error above
../vendor/bin/drutiny

I am using Drupal 8.4.5, PHP 7.1, Drush 8.1.15

**Comment by fiasco** [comment]
This is probably because you're trying to run directly from drutiny opposed to the `bin` directory provided by composer which lives in `vendor/bin` by default. Try `./vendor/bin/drutiny policy:list`.

**Comment by ainsofs** [comment]
newbie mistake. You are correct running ./vendor/bin/drutiny policy:list ran without problems

**Comment by ainsofs** [comment]
Sorry I thought it was resolved. So it seems when I run `./vendor/bin/drutiny` from my app root directory it runs fine but it cannot read my drush aliases which are located in web/sites/all/drush/

I get the error below:

`[Symfony\Component\Process\Exception\ProcessFailedException]`
`  The command "drush site-alias @dev --format=json" failed.`
`  Exit Code: 1(General error)`
`  Working directory: /var/www/html`
`  Output:`
`  ================`
`  Error Output:`
`  ================`
`  Not found: @dev                                                             [e`
`  rror]`

When I run from the web directory, I can see my aliases ie `drush @dev status` command

But cannot run drutiny properly `.././vendor/bin/drutiny` gives previously stated error

**Comment by fiasco** [comment]
drutiny expects drush to be globally executable and drush expects aliases to be in $HOME/.drush. 

If you type `drush sa` from your home directory, it should show you which aliases are available to you globally.

**Comment by ainsofs** [comment]
confirmed working once I copied my drush aliases to $HOME/.drush

thnx
