### ISSUE TITLE
 There are no commands defined in the "policy" namespace.

### ISSUE THREAD

**Issue by ainsofs** [seanhamlin/site-audit#162]
After doing a workaround for this issue https://github.com/drutiny/drutiny/issues/161

I tried to execute policy:list and get this error

` [Symfony\Component\Console\Exception\CommandNotFoundException]
  There are no commands defined in the "policy" namespace.`

**Comment by fiasco** [comment]
What happens when you run `./vendor/bin/drutiny list` ?

**Comment by ainsofs** [comment]
Sorry pls ignore. I've resolved it with https://github.com/drutiny/drutiny/issues/161 thnx
