### ISSUE TITLE
Allow policies to be output in a particular order

### ISSUE THREAD

**Issue by bschilt** [seanhamlin/site-audit#167]
The order in which policies are output in HTML reports cannot be controlled. Some reports are more informational as opposed to pass/fail so it would make sense to have the policy data show up in a predefined arrangement. 

Perhaps some sort of weight attribute can be added to the profile.yml file?

**Comment by fiasco** [comment]
In HTML reports, policies are ordered by default by Failures, Errors, Warnings, Notices, Passes and Not Applicable. Within each of those outcomes, policies are ordered by highest severity first. Beyond that, the ordering is natural based on how they fall in the policy and how the `PolicyChain` sorts them based on dependencies.

The biggest issue here is profile inheritance. How should the order of policies be handled if a profile pulls policies in from multiple profiles? We could preserve policy order in the profile but can't determine if inherited profiles should be appended to the bottom/top or integrated.

### Example: 

I have a profile called **profile_Z**. 
* profile_Z includes the policies `a`, `b` and `c`.
* profile_Z also includes **profile_Y** and **profile_X**
* profile_Y contains policies `d`, `e` and `f`
* profile_X contains policies `a`, `e` and `g`
* policy `b` also depends on policy `f`.

### Sorting outcomes
* natural order: `a, b, c, d, e, f, g` 
* dependency order: `f, a, b, c, d, e, g`
* commonality order: `e, f, a, b, c, d, g`
* equal weighting order: `a, d, b, e, c, f, g`

However, it may make sense for the report to list in an arbitrary fashion `g, c, d, a ,b, e, f` which we'd have no way to order at this stage.

Dependency order probably is the best option we could implement as it allows a policy ensure another policy precedes it but doesn't guarantee however that the policy will immediately precede it.

**Comment by fiasco** [comment]
Dependency ordering is current the default in 2.1.x branch. The default HTML reporting also groups policies by severity which can be overridden in a profile by providing your own content layout.
