### ISSUE TITLE
Broken logo

### ISSUE THREAD

**Issue by seanhamlin** [seanhamlin/site-audit#172]
Refers to https://raw.githubusercontent.com/drutiny/drutiny/2.x/assets/logo.png and appears in the README and the default templates.

**Comment by fiasco** [comment]
Should be fixed now with ref:8b10bd2

**Comment by seanhamlin** [comment]
Still a reference in https://github.com/drutiny/drutiny/blob/2.1.x/README.md

**Comment by fiasco** [comment]
Looks ok to me.
