### ISSUE TITLE
Severity categories

### ISSUE THREAD

**Issue by shanefjordan** [seanhamlin/site-audit#176]
The following severity categories are currently utilized:

- none
- low
- normal
- high
- critical

When providing output to customers, the **normal** severity level may be perceived as being correct. I'd recommend changing this level to **medium** instead. This falls into the other classifications and gives more weight to the severity level when listed in output.

**Comment by fiasco** [comment]
I had contemplated **medium** when I wrote this but thought **normal** was more appropriate. Though I didn't do any research around that. Doing a quick google search, I can see medium is used more commonly than normal so happy to change it to medium.

**Comment by fiasco** [comment]
I've done the renaming but left "normal" references in the codebase so that policies marked with this severity remain backwards compatible.
