### ISSUE TITLE
Enable domains.yml to be passed as input source for domains

### ISSUE THREAD

**Issue by markf3lton** [seanhamlin/site-audit#179]
As a Drutiny user I would like to pass a file listing all the domains to Drutiny and have it iterate for each domain in a multisite.

Looks like in https://github.com/drutiny/drutiny-legacy , domains were specified in  a yml and then called with a `--domain-file=domains.yml` in the command itself.

**Comment by cdulude** [comment]
++

**Comment by fiasco** [comment]
Just committed 25b93e07e18a37abc03b493849270b100bfe6e97 which adds support for domain.yml
