### ISSUE TITLE
Update chartjs colors to reflect typical pass/fail/error/warning colors

### ISSUE THREAD

**Issue by briantully** [seanhamlin/site-audit#187]
The ChartJS charts look awesome! However I think it would be nice to update the chart colors so that the colors better reflect typical pass/fail/error/warning paradigms.

currently they are set to:

<img width="1204" alt="current-chart-colors" src="https://user-images.githubusercontent.com/82321/40455271-37aa31c6-5eba-11e8-837a-8b6dd9d17c63.png">

pass = turqoise
fail = green
error = blue
warning = purple

Whereas, I'd like to propose:

<img width="1225" alt="updated-chart-colors" src="https://user-images.githubusercontent.com/82321/40455228-088144c0-5eba-11e8-8684-233ce93c07e6.png">

pass = green
fail = red
error = orange
warning = yellow

**Comment by fiasco** [comment]
I've updated Drutiny so the charting capability supports the ability to set your own colors:

![image](https://user-images.githubusercontent.com/108160/40519286-64e17cac-5ff1-11e8-82a0-139dba098757.png)

I also updated the severity stats template to use the colors you've suggested. Thanks!

**Comment by briantully** [comment]
That’s awesome, Josh! Thanks so much for doing that :)

You rock 🤘
