### ISSUE TITLE
The Drush driver should log the command and the response under -vvv

### ISSUE THREAD

**Issue by seanhamlin** [seanhamlin/site-audit#191]
Previous `2.1.x` behaviour was to log both the command and the response when supplied with `-vvv`. Now only the command is logged, making it impossible to find what went wrong.

Related to the commit https://github.com/drutiny/drutiny/commit/58f44e90a1662e58611abb2d256c6c2f857b24a6#diff-9ae4cf662e2cbc05514e68cad51a77ae

**Comment by fiasco** [comment]
I believe this is fixed. Please re-open if not.
