### ISSUE TITLE
ModuleEnable is broken

### ISSUE THREAD

**Issue by shanefjordan** [seanhamlin/site-audit#207]
Any functions that utilize the ModuleEnable are currently broken. It looks as though the functions are not being provided the JSON information for processing.

If I run the MOduleDisable function, the JSON data is provided for processing.

The function to check for **Enable** appears to be correct.

**Comment by fiasco** [comment]
Hey @shanefjordan  do you have an example to replicate? I'm not sure what I'm looking for.

**Comment by shanefjordan** [comment]
@fiasco I sent you details privately.

**Comment by shanefjordan** [comment]
This issue has been resolved in the 2.x-drutinyv2.3.x release.
