### ISSUE TITLE
Call to undefined function Drutiny\bcsub()

### ISSUE THREAD

**Issue by lolandese** [seanhamlin/site-audit#210]
Version: 2.3.1
OS: Ubuntu 18.04.1 LTS (LAMP without a VM)
PHP 7.2.7-0ubuntu0.18.04.2 (cli) (built: Jul  4 2018 16:55:24) ( NTS )

This is likely a support request as it might be me having set it up wrong. I am using Drutiny for the first time. Because I already had version 4.0 of the _symfony/cache_ package in my project, instead of using the recommended:
```
composer require --dev drutiny/drutiny 2.3.*@dev
```
I had to first remove the _symfony/cache_ package, manually add `"drutiny/drutiny": "2.3.*@dev",` to the _coposer.json_ and run _composer update_ for the two conflicting packages. That downgraded _symfony/cache_ to version 3.4.15 that was both acceptable for Drutiny and symfony/expression-language v3.4.15 (requires symfony/cache ~3.1|~4.0). All seemed fine after that. I was getting correct output for:
```
./vendor/bin/drutiny audit:list
```
But on:
```
 ./vendor/bin/drutiny policy:list
```
I get:
```
martin@margaretha-M1M3XBP-00:/var/www/html/mysite$ ./vendor/bin/drutiny policy:list
PHP Fatal error:  Uncaught Error: Call to undefined function Drutiny\bcsub() in /var/www/html/mysite/vendor/drutiny/drutiny/src/Utility.php:55
Stack trace:
#0 /var/www/html/mysite/vendor/drutiny/drutiny/src/PolicySource/PolicySource.php(64): Drutiny\_UtilityTimer->stop()
#1 /var/www/html/mysite/vendor/drutiny/drutiny/src/Command/PolicyListCommand.php(39): Drutiny\PolicySource\PolicySource::getPolicyList()
#2 /var/www/html/mysite/vendor/symfony/console/Command/Command.php(251): Drutiny\Command\PolicyListCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/html/mysite/vendor/symfony/console/Application.php(946): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/html/mysite/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(Drutiny\Command\PolicyListCommand), Objec in /var/www/html/mysite/vendor/drutiny/drutiny/src/Utility.php on line 55
```
BTW I got it working with a dirty hack simply using:
```
    return $this->end - $this->start;
```
instead of:
```
    return bcsub($this->end, $this->start, 2);
```
But looking at http://php.net/manual/en/function.bcsub.php we'll see the function itself is supported in PHP 7. Might it be due to the namespace prefix (Drutiny\bcsub())? Probably the answer to my question is plain simple and it's just me being puzzled.

**Comment by jacov** [comment]
+1 i have the same exact problem

**Comment by jacov** [comment]
Fixed with:
`sudo yum install php-bcmath`

**Comment by lolandese** [comment]
Yes. I looked over the fact that the page http://php.net/manual/en/function.bcsub.php is actually in the section of Mathematical Extensions (not making part of PHP "core"):

To add the dependency to the require section of the _composer.json_:

`        "ext-bcmath": "*",
`

See for more info http://syrwebdev.com/composer/2015/01/07/using-composer-to-require-php-modules.html.

**Comment by fiasco** [comment]
Thanks @lolandese I'll add that in
