### ISSUE TITLE
Return non-zero status on policy failures

### ISSUE THREAD

**Issue by fiasco** [seanhamlin/site-audit#211]

**Comment by fubarhouse** [comment]
There is a Audit severity (critical) which is largely undocumented and rather appropriate for this particular issue. How receptive would you be to taking better advantage of this in the context of appropriate exit codes? Low, Medium and High are all adequate however critical implies you want the application to fail if a critical requirement isn't met (Audit x or y passing for example).

**Comment by fiasco** [comment]
I hadn't contemplated incorporating severity into this feature but it makes sense!

**Comment by fubarhouse** [comment]
I have a primitive first-pass at this which does work and gives it the flexibility of future refinement, I'll be submitting a PR shortly for review. I would love some feedback if you can spare some time.
