### ISSUE TITLE
Add path/binary name for drush

### ISSUE THREAD

**Issue by fubarhouse** [seanhamlin/site-audit#220]
In the event a Drupal 7/8 site needed to be audited through the same entry-point, Drush immediately becomes only available to one site because it has one identifier and one location. So, Drupal compatibility is limited in any point in time.

Drush 9 is only available for Drupal 8, and Drush 9 does not work for Drupal 8 after 8.x-3.x.

Standard practice is to have two executables such as `drush8` and `drush9` or similar.

It would be practical in these cases to provide a name of the executable in `$PATH` at bare minimum, or more practically it would be ideal to provide the path to `drush` instead of trying to find it inside `$PATH` using `drush-launcher` or `which`.

**Comment by fiasco** [comment]
We do actually look for different versions of Drush. We even inspect the Drupal site to figure out which Drush version should be used. See https://github.com/drutiny/drutiny/blob/2.3.x/src/Driver/DrushRouter.php#L35

**Comment by fubarhouse** [comment]
Just to be clear: the idea is to have multiple available executables with the name `drush` available in `$PATH`, and Drutiny checks the versions of each looking for an applicable version based on the target alias?

I'll give this a go tomorrow.

**Comment by fiasco** [comment]
Not quite. Drutiny first looks for a drush binary with a preference for drush launcher (https://github.com/drush-ops/drush-launcher). If the launcher is found, then drutiny expects it to be the one that sources the correct drush version for the Drupal site (such as the one typically in `vendor/bin` for D8 sites).

The DrushRouter in Drutiny takes the found drush bin and acquires Drupal information from it (`drush status`). We then pass that through a switch statement to determine if the version of drush ought to change. The specific use case here is Acquia Cloud where drush 9 is not default, instead, sites using 8.3 or later need to reference `drush9` instead.

**Comment by simesy** [comment]
drush-launcher is supposed to be installed at `drush`. 

Handling fallbacks is:
```
export DRUSH_LAUNCHER_FALLBACK=/path/to/drush
```
