### ISSUE TITLE
2.3.3 not available yet on packagist

### ISSUE THREAD

**Issue by tobybellwood** [seanhamlin/site-audit#225]
the recent 2.3.3 release has not appeared on packagist yet ;-)
https://packagist.org/packages/drutiny/drutiny

**Comment by fiasco** [comment]
> This package is using the legacy service integration that GitHub deprecated in January 2019 and will not auto-update anymore. Please set up the new GitHub Hook for Packagist so that it starts updating again.


I've manually updated it for the time being but I'll need to establish new webhooks.

**Comment by tobybellwood** [comment]
beautiful - thanks for the continued attention @fiasco 💯
