### ISSUE TITLE
Support Twig v2

### ISSUE THREAD

**Issue by robertromore** [seanhamlin/site-audit#230]
Is it possible to support Twig v2? According to [this page](https://www.drupal.org/docs/8/theming/twig), with the release of Drupal 8.7, Twig v2 is supported by Drupal. Currently trying to use this project with Twig v2 results in a dependency requirement issue since this project is locked to using Twig v1.

**Comment by fiasco** [comment]
Its recommended to run Drutiny in isolation from your Drupal codebase to prevent dependency conflicts. 

Supporting Twig v2 (and removing moustache) is a good idea though.
