### ISSUE TITLE
Audit report should not check for collation consistency on __ACQUIA_MONITORING table

### ISSUE THREAD

**Issue by darenschaad** [seanhamlin/site-audit#239]
It seems that there is a false positive that comes up often that leads the customer to believe that they need to convert the __ACQUIA_MONITORING table from utf8_general_ci to utf8mb4_general_ci if that is the default collation.

Can we have the report ignore this table?

![screenshot_2020_01_07-13_20_29 59](https://user-images.githubusercontent.com/16549137/75078345-38187a80-54ba-11ea-9ac5-50c168353dfa.png)

**Comment by fiasco** [comment]
We've resolved this in the Acquia policy repository which is currently not publically available :( 
We're working on resolving this.
