### ISSUE TITLE
Running profiles with 1-month duration produces unexpected data output 

### ISSUE THREAD

**Issue by sethhill** [seanhamlin/site-audit#241]
When running a Drutiny profile with a specified reporting period of 1 month, data tables are being generated with 30-second intervals. This causes long page render times and unreadable graphs. It appears that the reporting duration is being calculated as 0.

**To Reproduce**
The command run to produce the error:
```
drutiny profile:run d8_health_analysis @drupalvm.vm --reporting-period-start=2020-04-01 --reporting-period-end=2020-05-01
```

**Comment by fiasco** [comment]
Significant find @sethhill thanks! Can you please attach a before and after screenshot of the graphs to clearly articulate the problem and proof of the solution? After that, I'll be happy to merge.

**Comment by sethhill** [comment]
No problem @fiasco. Let me know if there's anything else you need here.

**BEFORE**, showing unexpected grouping of data. Underlying data table has 10,000 rows, and page takes approximately 34 seconds to render with graphs:
<img width="1447" alt="drutiny-graph-BEFORE" src="https://user-images.githubusercontent.com/3334926/81755814-a859eb00-946e-11ea-8537-75a11bd6c789.png">

**AFTER**, showing expected grouping of data. Underlying data table has 60 rows, and page takes around 1 second to render with graphs:
<img width="1445" alt="drutiny-graph-AFTER" src="https://user-images.githubusercontent.com/3334926/81755816-aabc4500-946e-11ea-825e-77dda8669f0d.png">

**Comment by fiasco** [comment]
Thanks Seth! Merged and closed.
