### ISSUE TITLE
Console output truncating tabular data

### ISSUE THREAD

**Issue by sethhill** [seanhamlin/site-audit#243]
When running profiles or individual policy audits, some tabular data is excluded from display. This seems to occur only in the Console view, as running an identical report to HTML output contains the full data.

**Expected behavior**
Data in Console should be complete and match HTML output.

**Screenshots**
Underlying tabular data from HTML output:
<img width="953" alt="Screen Shot 2020-05-15 at 11 28 01" src="https://user-images.githubusercontent.com/3334926/82083959-65328e80-969f-11ea-8c4e-fadcb93f3cb3.png">

Tabular data as displayed in Console:
<img width="733" alt="Screen Shot 2020-05-15 at 11 22 35" src="https://user-images.githubusercontent.com/3334926/82083985-6ebbf680-969f-11ea-9f24-54754cf99f1c.png">

**Comment by fiasco** [comment]
Thanks for the contribution!
