### ISSUE TITLE
SqlResultAudit doesn't allow non-select queries.

### ISSUE THREAD

**Issue by joshirohit100** [seanhamlin/site-audit#249]
The query I am trying to run was `SHOW VARIABLES LIKE 'tx_isolation'` to check the transaction isolation level but `SqlResultAudit` only allows select query as per -
```
if (!preg_match_all('/^SELECT( DISTINCT)? (.*) FROM/', $query, $fields)) {
   throw new \Exception("Could not parse fields from SQL query: $query.");
}
```

**Comment by joshirohit100** [comment]
PR #248 https://github.com/drutiny/drutiny/pull/248

**Comment by fiasco** [comment]
Thanks for the contribution!
