### ISSUE TITLE
Contributing platform specific policies - question

### ISSUE THREAD

**Issue by bomoko** [seanhamlin/site-audit#264]
Hi there,

This is really a question about the appropriate approach to contributing platform specific policies to Drutiny.
In the last year my team in Amazee Labs has started to make serious use of Drutiny internally, it's a great tool and we're getting a ton of use out of it.

We're also writing a fair number of policies, some of which might make sense to try get back into the project.

A subset of the policies we're writing target Amazee.io's platform, Lagoon.

I was wondering if, like with the Acquia, cloudflare, and Sumologic audit policies, whether it would be possible (and even appropriate) for us to submit amazee.io/Lagoon specific audits directly to the Drutiny project?

This would certainly simplify installation and discoverability from the Lagoon/Drupal users' perspective - although I totally understand if it's more appropriate for it all to live in a separate repository (we've already got a fork we're using, but I'd like to get away from that for most clients if possible).

Any advice/insight here would be greatly appreciated. 
Thanks in advance.

**Comment by fiasco** [comment]
Hey @bomoko, great question!
At Acquia we've been building out a lot of policies for our platform too. As adoption across the company has grown, we needed better tooling then github could provide to make policy building more accessible to less technical folk.

As such we've migrated policies and profiles into a Drupal site and pull them over a restful API. This also allowed us to decouple policy and profile building from drutiny console development. If you use the Acquia plugins today, you'll notice many policies now come from our plugin opposed to the github community. To that end, we've stopped maintaining the community policies.

In Drupal, we're able to leverage content discovery, workflow and translations in ways github and YAML just didn't cut it. We still lacked workflow conversation though and so also run an internal JIRA project for that.

The downside of this approach is that its not open or collaborative with our customer community, partner community or even our competitors like yourself. That said, in drutiny 2.x, you can list your own 3rd party policy and profile sources so you're free to do exactly that. You can even blend multiple sources together.


I'd be happy for the Drutiny org on github to host an Amazee plugin if you like, but a drutiny plugin under your own org works just as good too. As for policies and profiles, I had been thinking about removing them entirely from the repos and focusing Drutiny work on the console and allowing source providers to focus on the policy and profile content.

**Comment by bomoko** [comment]
Brilliant, thanks so much for the response @fiasco - that all makes a lot of sense.

I think for now we'll go with hosting it under our own org, and if there is anything that comes out that's particularly compelling and/or generic, we'll figure out a way of contributing it back to one of the more generic plugin repos.

Thanks again!
