### ISSUE TITLE
Support for vendor Drush

### ISSUE THREAD

**Issue by adam-bergstein** [seanhamlin/site-audit#284]
The readme highlights the following command, which installs Drush globally:

`composer global require drush/drush:dev-master`

Can Drutiny be run with a vendored Drush?

**Comment by fiasco** [comment]
Look like drutiny uses versions of symfony that are too far ahead. We'd have to port drutiny back to symfony 4 or ensure drush could run on Symfony 5 first.

```
» composer require drush/drush                                                                                                                                       [±3.0.x ●]
Using version ^10.5 for drush/drush
./composer.json has been updated
Running composer update drush/drush
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires drush/drush ^10.5 -> satisfiable by drush/drush[10.5.0].
    - drush/drush 10.5.0 requires symfony/event-dispatcher ^3.4 || ^4.0 -> found symfony/event-dispatcher[v3.4.0, ..., v3.4.47, v4.0.0, ..., v4.4.20] but it conflicts with your root composer.json require (^5.0).

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

```

**Comment by fiasco** [comment]
Drutiny uses many underlying 3rd party tools including docker, docksal, lando, ddev and more. Its not feasible to define all of these as dependencies nor manage version compatibility maps. So instead, we'll leave drush out as a dependency but allow profiles and policies to define version requirements if they wish.
