### ISSUE TITLE
Is there a reason that paragonie/random_compat is locked at version ^2.0 ?

### ISSUE THREAD

**Issue by lems3** [seanhamlin/site-audit#287]
When I try to add Drutini to my project, I get a dependency error.

We dug in it and found out that "Acquia Lightning" at one point allows paragonie/random_compat version higher than 2. Which had us intall and lock version 9.99.100

On paragonie/random_compat README, we can read the following info : 

> Version 9.99.99
> Note: There is a special version called 9.99.99 which makes this library do nothing, but is only installable on PHP 7.
> If you're writing software (e.g. a library) that supports PHP 5, but may be used by software that doesn't, you'll want to allow 9.99.99 to be installed. The above diff is what you want.

If I'm not wrong (I may be), that means we're ok with version 9 when using PHP7 or later.

Being new to Drutini (trying to install it for the first time), I don,t know if this dependency to version 2 is mandatory. 😄

**Comment by fiasco** [comment]
Drutiny doesn't use this library.

**Comment by lems3** [comment]
It was indeed removed in v3. Thanks!
