### ISSUE TITLE
Convert README into actual documentation book

### ISSUE THREAD

**Issue by seanhamlin** [seanhamlin/site-audit#54]
I think now the amount of information we need to convey now exceeds a single page. I would love to integrate with github pages or similar using the docs folder https://github.com/blog/2233-publish-your-project-documentation-with-github-pages.

Another option is gitbooks.io

**Comment by guitarte** [comment]
There's also https://readthedocs.org/ which [BLT](http://blt.readthedocs.io/en/8.x/) uses.

**Comment by seanhamlin** [comment]
Awesome, thanks @guitarte, I think at this point I just want something that works and is easy to maintain in git. I actually had a stab at read the docs with http://drutiny.readthedocs.io/en/latest/ but I need to learn http://www.sphinx-doc.org/en/stable/ by the sounds.

If you have experience here, keen for help getting this started.
