### ISSUE TITLE
Entity Reference Remediation

### ISSUE THREAD

**Issue by steveworley** [seanhamlin/site-audit#56]
The output for the entity reference check shows the machine name for the field- but checks configurations per field definition and doesn't tells us exactly which field on which content type the configuration is broken- we should be able to update particular field configurations with a query to ease this.

Field conf looks like

```
'label' => 'Topics',
'widget' => array(
  'weight' => '6',
  - 'type' => 'options_select',
  - 'module' => 'options',
  + 'type' => 'entityreference_autocomplete',
  + 'module' => 'entityreference',
  'active' => 1,
  'settings' => array(
    'apply_chosen' => '1',
    'flatten_options' => 0,
    'flatten_sort' => 1,
  +  'match_operator' => 'CONTAINS',
  +  'size' => 60,
  +  'path' => '',
  ),
),
```

**Comment by fiasco** [comment]
This check wasn't ported to 2.x as it didn't align with the policy/audit architecture. Closing.
