### ISSUE TITLE
Please avoid the name collision with site_audit

### ISSUE THREAD

**Issue by fluxsauce** [seanhamlin/site-audit#57]
Howdy, neat tool! Fantastic to have more techniques and approaches to a common problem.

However, it's named the same thing as the existing utility https://www.drupal.org/project/site_audit - https://github.com/fluxsauce/site_audit

I respectfully request that you name it something distinct, as currently it's literally named the same thing as my existing project.

> Traditional site audits (e.g. the checklist API module or the site_audit module) in Drupal rely on having certain modules or code present on the server in order to gather the required metrics. The main issue is that if you fail to even have these modules enabled at all, then no auditing will take place in the first instance.

site_audit doesn't depend on any third-party modules, it integrates optionally with them if they exist, and it's not a module, it's a drush command with some initial Drupal Console support as well.

Thanks!

**Comment by wiifm69** [comment]
Hey @fluxsauce, yeah I have been thinking about naming this something better for a while now, I agree the crossover with the Drupal module is unfortunate (and certainly not intended). 

And the quote you mentioned above just means that you need to have those module actually on the website (and enabled), where as this tool does not depend on *any* code being deployed to your web servers. I can make this clearer still if you think this is confusing.

Open to ideas for a new name from anyone ;)

**Comment by seanhamlin** [comment]
Hey @fluxsauce, yeah I have been thinking about naming this something better for a while now, I agree the crossover with the Drupal module is unfortunate (and certainly not intended).

And the quote you mentioned above just means that you need to have those module actually on the website (and enabled), whereas this tool does not depend on any code being deployed to your web servers. I can make this clearer still if you think this is confusing.

Open to ideas for a new name from anyone ;)

**Comment by seanhamlin** [comment]
Can do something like Drush (Drupal Shell), and call it Druaud (Drupal Audit) or Drudit.

**Comment by fluxsauce** [comment]
Thank you for the prompt response, I appreciate it.

> certainly not intended

Given that you're explicitly naming `site_audit` as the reason why you created `site-audit`, given that you cite it in your documentation, and the similarity in commands (down to calling the atomic pieces "checks" and the structures) I don't understand that explanation. It's okay to take inspiration, but it seems disingenuous to say you weren't aware of it.

> And the quote you mentioned above just means that you need to have those module actually on the website (and enabled)

`site_audit` is not a Drupal module nor does it require any non-core Drupal modules for base functionality.

`site_audit` gracefully degrades and does not run checks for things that are not relevant and do not exist in the target system; for example, if `views` isn't available, it won't run the views checks. The vast, vast majority uses Drupal core - as your tool does. With that said, there are some file system traversals that utilize *nix commands due to efficiency and scale (designed to run on hundreds of thousands of sites on the same platform), which I'll freely admit.

It's okay to compare and contrast and I welcome different approaches, but please be accurate.

Regarding the name, as long as it's clearly distinct (IE not called `site audit`), it shouldn't be a problem. For example, `Drupal Audit` or `Druaud` is fine and I don't expect there will be confusion around that name.

**Comment by seanhamlin** [comment]
Hey @fluxsauce, the README was added much later in this project, and the references to related tools were again [added much later](https://github.com/seanhamlin/site-audit/commit/139ae2862183e4655b1584236d982bd3ee545091#diff-04c6e90faac2675aa89e2176d2eec7d8), I was aware of the checklist API module, but not your project initially (see a [follow up commit](https://github.com/seanhamlin/site-audit/commit/232082dfa07564286df6d83305a7f8f0d2e20da8#diff-04c6e90faac2675aa89e2176d2eec7d8) 7 days ago).

I was not aware that `site_audit` was not a Drupal module (I had not looked at the code to be completely honest).

Now that I have looked at both codebases, I can still see a point of difference between the 2 projects:

* `site_audit` is drush based tool, which you can run against a system (local and remote), no Drupal module is needed, but can be extended with some (optionally). Checks can be excluded from being run with `--skip`. There appears to also be some Pantheon integration as well. Custom Checks are Drupal hooks. Example check from the codebase [page compression](http://cgit.drupalcode.org/site_audit/tree/Check/Cache/PageCompression.php).
* `site-audit` (or whatever the new name will be) is a Symfony Console application which can audit sites using Drush, SSH, Phantomas (and can be extended). Profiles are made for your own "best practice" (some are supplied), and Checks can be run in any order (or excluded), and have optional arguments supplied to customise the checks further. Checks are simple annotated classes. Example check from the codebase [page compression](https://github.com/seanhamlin/site-audit/blob/master/src/Check/D7/PageCompression.php).

One of the founding principles for this application was to stop "best practise" being forced upon you, when in reality what you consider best practice may depend on your website and what it does, your development team etc.

I will update the README today to reflect the above, sorry about that confusion.

**Comment by seanhamlin** [comment]
Just updated the README to help better clarify things https://github.com/seanhamlin/site-audit/commit/013f746fa47c6562a29e4c2101907f1e1b41bea9. I am also working with a few people to determine the best name to change this to, will perhaps have a better idea on this in around 1 week.

**Comment by fluxsauce** [comment]
Thank you, I appreciate it.

**Comment by seanhamlin** [comment]
PR is now open while I work the kinks out https://github.com/seanhamlin/site-audit/pull/61, in short the new name will be Drutiny. I will rename the repo after the merge.

**Comment by seanhamlin** [comment]
Merged in PR, renamed git repo. For all the forks out there, I will reach out and get them to update their remotes.

**Comment by fluxsauce** [comment]
Thank you.
