### ISSUE TITLE
Create logo for project

### ISSUE THREAD

**Issue by seanhamlin** [seanhamlin/site-audit#79]
Also use it in the HTML report

**Comment by theodorosploumis** [comment]
Let me help.
I am a Drupal *er but I like creating logos, just for fun. Especially when it comes to Drupal! 
Will come back soon with some proposals if you like.

**Comment by seanhamlin** [comment]
Thanks, that would be amazing!

**Comment by theodorosploumis** [comment]
Here you are. 

I tried to make the logo a bit "serious" and flat because we talk about auditing and remediation but I must confess I prefer No 5 mostly (which is somehow playful)! Notice the the wording will be according to the logo so let's first choose the logo.

I also tried to not use/include the original Drupal logos somehow since there is a different logo for 7.x and 8.x as also as to avoid license issues.

![proposals_drutiny](https://cloud.githubusercontent.com/assets/1315321/24262082/a0b9196a-1001-11e7-842a-1a902150065b.png)

**Comment by fiasco** [comment]
Thanks for the contribution! Its nice to have some design for such a headless tool.
1 and 3 are my favourites. 5 the least purely because it has writing in it (see TED talk on flags: https://www.ted.com/talks/roman_mars_why_city_flags_may_be_the_worst_designed_thing_you_ve_never_noticed applys for icons too IMHO).

**Comment by markgifford** [comment]
Nice logos! I'd go with either 4 or 5

**Comment by hoff331** [comment]
great work @theodorosploumis, my vote is for option 1 or 2.

**Comment by seanhamlin** [comment]
Hey @theodorosploumis, thanks for taking the time to do these! I have asked a few colleagues to weigh in as well. Initial thoughts:

* flat design works well
* agree with not using the drupal logo
* I think # 3 has potential, kind of reminds me of a mash up between the drush cog logo (but flat), and a magnifying glass which I like.
* I also like # 1, Drutiny at it's heart is all about ensuring the site meets your own best practice, so having a tick is quite a nice symbol

**Comment by markgifford** [comment]
Something else I wanted to add: though number 3 looks really good, I would associate it with a config tool more than an audit tool

**Comment by theodorosploumis** [comment]
I also like No1. It is unique (at least as far as I know), modern and business oriented. Should I continue with No1 or wait for more comments?

**Comment by seanhamlin** [comment]
@theodorosploumis I have asked a few more people to weigh in (based in Australia, so they are just waking up). I might also send a tweet out as well. So I would hold fire for now.

**Comment by gollyg** [comment]
I like 3 as a pleasing icon, but agree it feels more like a config button. For me that would leave 1 and 2. I think that 2 is more interesting - if you were going with 1 I think that it need a little more balance.

But overall, what a great job @theodorosploumis !

**Comment by seanhamlin** [comment]
Had a vote for # 5 as well from twitter https://twitter.com/lauraa_munro/status/845026939597287424

**Comment by stooit** [comment]
My vote is for 1, I think it's the clearest indication of what Drunity is actually doing. Nice one @theodorosploumis!

**Comment by seanhamlin** [comment]
Hey @theodorosploumis, so it seems like # 1 is perhaps the most liked out of the bunch, so I would continue down that road, some really interesting feedback here too.

I forgot to mention, I am happy to mention your name (and website) in the README if we can have the logo in the project.

**Comment by theodorosploumis** [comment]
![final_proposals](https://cloud.githubusercontent.com/assets/1315321/24306465/5de7706e-10c9-11e7-932b-6ae9177a5b27.png)

**Comment by theodorosploumis** [comment]
I would vote for No2!

**Comment by seanhamlin** [comment]
Wow, thanks @theodorosploumis!, I also like the 'D' part of # 2, I think the large tick really works. I am not a fan of the remaining font used for 'rutiny' though, seems a bit cartoony and not professional.

Keen to hear what other people think as well.

**Comment by theodorosploumis** [comment]
You are right, the font is not professional enough. Will come back with a more professional looking one.

**Comment by theodorosploumis** [comment]
Let's not use a font for the tool name but only the logo. Something like this.
![poposals_drutiny_v2](https://cloud.githubusercontent.com/assets/1315321/24321947/70c5a55e-1162-11e7-897d-4a98b12cddf9.png)

**Comment by seanhamlin** [comment]
I agree, having words with the icon does not seem necessary, as the icon alone looks great. I also still think # 2 looks the best.

I am happy to progress this issue, i think what we need from here:

* SVG version of the icon
* 260x260 PNG with transparency (if appropriate)

Then a PR can be made that (I am happy to do this):

* Updates the README.md file with the logo, and the attribution for @theodorosploumis 
* Updates the HTML reports with the logo (both in the report, and the favicon)

**Comment by theodorosploumis** [comment]
[Logo_Drutiny.tar.gz](https://github.com/seanhamlin/drutiny/files/872886/Logo_Drutiny.tar.gz)

I could not remove the white background from the checklist on svg but png images are OK.

I will make a PR soon.

**Comment by seanhamlin** [comment]
Wow, thanks @theodorosploumis, SVG is looking nice. I was able to run it through a [minifier](https://jakearchibald.github.io/svgomg/) to reduce it's size (and make it more inline-able)

```
<svg xmlns="http://www.w3.org/2000/svg" width="500px" height="500px" viewBox="0 0 500 500"><defs><clipPath id="a"><path style="isolation:auto;mix-blend-mode:normal" color="#000" overflow="visible" solid-color="#000000" fill="#b3b3b3" stroke-width="4" stroke-linecap="round" stroke-linejoin="round" d="M299.59 94.2306h72.9858v83.5515h-72.986z"/></clipPath><clipPath id="b"><path transform="translate(-80.098)" clip-path="url(#a)" d="M320.6388 154.571c-.4562-.0867-1.7168-.8433-5.1238-3.0754-6.7964-4.4526-24.85-16.936-25.1635-17.3996-.3524-.521-.402-.9748-.1714-1.5686.218-.5615 6.3375-6.5197 7.0698-6.8835.6565-.3262 1.4764-.3683 2.1212-.109.3072.1236 4.5605 2.903 9.452 6.177 9.7585 6.5315 9.4377 6.3548 10.7143 5.898.6452-.231 1.2404-.85 20.9323-21.765 6.2976-6.6888 11.452-12.053 11.673-12.1486.5622-.243 1.3545-.2986 1.9335-.136.7502.2108 8.4062 5.3106 8.761 5.836.3913.5796.4348.997.1702 1.6358-.3326.8032-40.2468 43.1138-40.948 43.4065-.6464.2697-.679.2728-1.4207.1303z" fill="#fff"/></clipPath></defs><text style="line-height:125%" x="326.7844" y="199.7935" font-size="15" font-family="sans-serif" letter-spacing="0" word-spacing="0" transform="translate(-279.448 336.74)"/><path d="M.89.242h255.782V500H.89zM474.606 140.117c-60.028-123.86-207.9796-175.048-330.383-114.3054C21.8194 86.5538-28.7666 236.2657 31.2617 360.1254c60.028 123.86 207.9795 175.048 330.383 114.3055 122.4036-60.7425 172.9897-210.4544 112.9614-334.3142z" style="isolation:auto;mix-blend-mode:normal" color="#000" overflow="visible" solid-color="#000000" fill="#2ba9e0"/><path d="M474.4445 140.1167C430.05 45.6625 322.1122-12.5973 219.2288 2.322c-97.962 11.7782-184.456 87.6233-208.1703 184.19-27.9065 99.8675 15.0932 213.8845 101.204 270.6782 81.6323 57.0215 197.1573 56.7308 278.6272-.3178 86.45-57.2443 128.7883-172.2813 100.2707-272.331-4.153-15.297-9.7704-30.1893-16.716-44.4247z" fill="#2ba9e0"/><g transform="matrix(7.62077 0 0 7.59736 -1672.36 -742.468)" clip-path="url(#b)" fill="#fff"><path d="M281.6857 115.892c-7.9725-16.303-27.6223-23.0407-43.879-15.0455-16.2568 7.9952-22.9753 27.701-15.0028 44.004 7.9724 16.303 27.6223 23.0406 43.879 15.0454 16.2567-7.9953 22.9752-27.701 15.0027-44.004z"/><path style="isolation:auto;mix-blend-mode:normal" color="#000" overflow="visible" solid-color="#000000" d="M219.5647 97.481h33.5638v65.7804h-33.5638z"/></g></svg>
```

**Comment by seanhamlin** [comment]
@theodorosploumis let me know how you are getting on with the PR, I do see a few commits on your fork https://github.com/seanhamlin/drutiny/compare/master...theodorosploumis:master. Happy to help out.

**Comment by seanhamlin** [comment]
Related to PR #86
