### ISSUE TITLE
D7 GA check unhelpful

### ISSUE THREAD

**Issue by NigelCunningham** [seanhamlin/site-audit#81]
Hi.
Your tool is included in the site audit for govCMS. While running those checks on a site that had no special GA configuration, I received the D7 GA error. It would be much more helpful if it told you what its actually expecting you to have in the "Code snippet (after)" field. Pull request coming shortly to do just that.
Thanks for your work.

**Comment by seanhamlin** [comment]
Thanks for the submitting the issue, PRs are welcome. Potentially this could be auto-remediated as well.

**Comment by NigelCunningham** [comment]
Totally agree. Sorry but I was just doing what I need to while under the pump :)

**Comment by seanhamlin** [comment]
No worries, appreciate any input here.
