### ISSUE TITLE
Bundle into a .phar and use releases

### ISSUE THREAD

**Issue by steveworley** [seanhamlin/site-audit#85]
It might be a good idea now that the project has some CI that we could add a build that would create a `drutiny.phar` file that could be downloaded from the Github releases page.

Can use this https://github.com/box-project/box2 (which can be included via composer) and a composer script that will build the project into a phar.

**Comment by seanhamlin** [comment]
I love this idea. And yes travisci could be extended so that on the successful build executes the build of the phar file, and somehow pushes that somewhere.

Would be nice to have tagged a stable release of Drutiny, and then we could version the phar files nicely too.

**Comment by seanhamlin** [comment]
Found a decent tutorial on this https://mwop.net/blog/2015-12-14-secure-phar-automation.html (uses box too).

**Comment by steveworley** [comment]
One thing I was thinking about with this is we should add the ability to find a Drutiny profile in the current directory (similar to phpunit) so we don't need to bundle "profiles". This would allow us install `drutiny` globally and use local profiles per site.

We might also look to include a `~/.drutiny` for global profiles.

**Comment by seanhamlin** [comment]
Totally agree. Ideally I only want the default profiles to remain in this repo, the rest should be moved into their own repos. See https://github.com/seanhamlin/drutiny/issues/84

**Comment by fiasco** [comment]
Drutiny is now an extensible framework. Building .phar releases would preclude that extensibility so I don't think it makes sense anymore in 2.x.
