### ISSUE TITLE
Allow profiles to specify HTTP or HTTPS

### ISSUE THREAD

**Issue by seanhamlin** [seanhamlin/site-audit#92]
At the moment phantomas assumes HTTPS but it would be nice to be able to make this configurable in the profile.

**Comment by fiasco** [comment]
There are checks now that check for HTTPS. They do this in a number of ways:

- Force an HTTPS connection and see if it connects. Won't connect if its not available or if cert is invalid.
- Force an HTTP connection and check for a redirect to HTTPS.

If such support was implemented, it would need to be done in a way that didn't break existing functionality. 

Right now, Drutiny assumes the user administering the audit knows which protocol to use.
