### ISSUE TITLE
[2.x] Documenting Check Metadata with YAML

### ISSUE THREAD

**Issue by fiasco** [seanhamlin/site-audit#94]
In 1.x, checks use doctrine annotations to define check metadata. It was done this way so that the metadata and the Check class itself were together in a single file. In this way it made checks more portable. But there were however, some downsides:

- In profiles, checks were specified by their Class and namespace which made them hard to compile and a DX barrier for contributors
- Annotations use a pseudo code syntax which requires the actual metadata to be passed in in datatypes like strings. This means the data needs to be escaped which makes readability harder.
- Text editors don't natively interpret annotations in comments providing no syntax highlighting
- PHP does not parse comments and cannot find syntax errors (though doctrine provides this). This i more of an issue in Drupal than in Drutiny.
- Multi-line data in annotations is ugly because of the `*` at the begining of each line. It makes management of these difficult.
- Annotations look better for defining small pieces of data and the plan in 2.x is to use metadata more efficiently.
- Adding HTML and markdown inside of annotations looks dirty and hard to read. It just feels like the wrong place to put annotations.

In 2.x, I re-introduced YAML as the metadata file for Checks. While this does decouple check metadata from the checks, it does make adoption from a DX standpoint easier (IMO)

- YAML is a more broadly used and common format. It doesn't require a predefined Annotation class to use it (this is also the reason why YAML is validated in runtime).
- The filename itself introduces a new naming format that is more DX friendly.
- YAML is more likely to be supported in text editors
- YAML has great multi-line support and doesn't hinder HTML or markdown and neither will require escaping.

One of the key differences between the two approaches is how they address structured data.

- In Annotations, you define a class and only properties of that class can be provided in the annotation.
- In YAML, there are no rules but the rules of the syntax, there is no guarantee of data structure.

Because check metadata requires structure, I also added to 2.x YAML validators at runtime which essentially is doing the same thing as Doctrine would be doing for Annotations. So this not to replace TravisCI validation but to provide more responsive feedback to Check developers and to allow more assumptions to be made in the framework about the data provided.

**Comment by seanhamlin** [comment]
Also useful background reading https://www.drupal.org/docs/8/api/plugin-api/annotations-based-plugins. I think we can learn from Drupal itself here, as they have gone through a similar exercise

> Why annotations?
>
> In contrast to other discovery mechanisms, the annotation meta-data lives in the same file and is an integral part of the class that implements the plugin. This makes it easier to find and easier to create a new custom plugin by simply copying an existing one.

I do agree that specifying the check by full namespace is silly and would be a fan of using some shorter version

e.g. 

```
  - performance.d7.process.css
```

or just

```
  - d7.process.css
```

We could write a wrapper to map this short class to the actual `Check` class. This would be easy to test as well.

So I guess the only issue left is does the addition of the extra YAML file per check justify it's benefits? Keen to hear from others in the community.

**Comment by fiasco** [comment]
A big difference between Drupal's use of annotations to Drutiny's is that Drutiny uses it to store **content**. For fields in Drutiny like description, success and failure, should be able to support multiple paragraphs of content with accompanying lists and tables. Drupal does not do this in annotations because it would be just straight out wrong. Because it is. Drupal's use of annotations is for developers and site builders to see and use while Drutiny's use for them in Checks in 1.x is exposed in an HTML report.

Using annotations, you'd be better off specifying a template file or similar in the annotation which then breaks the whole point of using annotations in the first place - to keep everything in one place. YAML is a compromise on that because the format is less intrusive and makes inline markdown and variable placeholders easier to read. But it lets you keep all the metadata inside a single file (opposed to a templating system which would require a file per template E.g. twig)

**Comment by steveworley** [comment]
I think @fiasco has the right of it- doctrine annotations in my experience are more for informing the controller class that how a property relates to the ORM rather than controlling output.

With a YAML configuration file you could manage your check short name in a property- the loader could load all YAML configuration files, find the ones that relate to your profile and then instantiate the referenced classes. Looking through the 2.x comparison- looks like you thought of this.

Tokens are my only concern with moving to full YAML based configuration files and it's more a convenience thing than anything- moving between files can become frustrating. Perhaps there is an opportunity to improve how tokens are handled via the checks.

**Comment by fiasco** [comment]
@steveworley I did introduce handlebars for token rendering. Tokens were renamed to "parameters". You can see [here](https://github.com/fiasco/drutiny/blob/2.x/src/Check/d8.page.cache.yml#L9) how they're used.
