### ISSUE TITLE
Missing installation instructions

### ISSUE THREAD

**Issue by jstoller** [seanhamlin/site-audit#96]
I don't see anything in the provided documentation about how to install drutiny. There's information on installing some of its requirements, but not on how to install drutiny itself.

**Comment by seanhamlin** [comment]
Hey @jstoller, do you mean you want to install drutiny globally to your PATH? Once you have run though the requirements steps in the README, you will have a functioning PHP application ;)

**Comment by jstoller** [comment]
@seanhamlin, I mean how do I get Drutiny on my computer, in the right place, so I can use it? The README explains how to install Composer and Phantomas, then jumps into using Drutiny, but it never actually says how to install this software.

**Comment by seanhamlin** [comment]
> how do I get Drutiny on my computer

git clone, composer install etc as per the instructions you mention.

> in the right place

You decide where to place it, this is up to you. Drutiny does not have an installer to place it into `/usr/local/bin/` for you, if this is what you are asking.

> jumps into using Drutiny

I am confused. Are you expecting a GUI? This is a CLI based tool, to which can create HTML reports, but the 'interface' is the command line.

**Comment by jstoller** [comment]
I realize this is a CLI tool. But generally when I install a CLI tool there is some command, or series of commands I'm supposed to run—be it curl, composer, npm, gem, wget, etc.—to download and install the software. Forgive me if this is too basic a question to ask. I spend a lot of time on the command line, but when it comes to system administration I know enough to be dangerous, so I like a little hand holding in the documentation. 

Based on your previous comment, I'm guessing the installation process is something like this:

1. Download drutiny and put it wherever you'd like on your system
2. In the command line, navigate to the drutiny directory: `cd /path/to/drutiny`
3. Run `composer install`

But the current README just has step #3, and only barely. It indicates that installing Composer is a requirement (without a link to those installation instructions, I might add), then without any context says:
```
composer install
```
I completely missed this because I thought it was talking about installing drutiny's prerequisites and I already have Composer installed. Nothing indicates where to execute that command, or that this is part of the drutiny installation, rather than the Composer installation. 

Maybe have someone who's not an Acquia TAM edit the documentation. ;-)

**Comment by seanhamlin** [comment]
Hey @jstoller, PR's welcome for the README, I realise that they are brief, and as you say, there are some people they may want them to be more verbose. I also would not be opposed to created a whole new `INSTALLATION.md` file or similar.

There is also another feature request #85 to bundle a phar file, if that happened then you would not need to do the step you mentioned with composer as well.
